In [2]:
import torch
x = torch.randn(3, requires_grad= True)
x

tensor([ 0.2273, -0.0492, -1.7472], requires_grad=True)

In [3]:
y = x + 3
y

tensor([3.2273, 2.9508, 1.2528], grad_fn=<AddBackward0>)

In [12]:
z = y*y*2
# z = z.mean()
z

tensor([20.8309, 17.4150,  3.1392], grad_fn=<MulBackward0>)

In [13]:
v = torch.tensor([0.1,  1.0, 0.001], dtype=torch.float32)

In [14]:
z.backward(v)

In [15]:
x.grad

tensor([ 5.5940, 15.7378,  1.6755])

In [30]:
a = torch.randn(3, requires_grad=True)
a

tensor([-0.8009,  0.7009,  0.8776], requires_grad=True)

In [23]:
# a.requires_grad_(Fasle)
# a.detach()
# with torch.no_grad();
a.requires_grad_(False)
a

tensor([-0.0199,  0.4952, -0.6442])

In [26]:
b = x.detach()
b

tensor([ 0.2273, -0.0492, -1.7472])

In [31]:
with torch.no_grad():
    c = a +2 
c

tensor([1.1991, 2.7009, 2.8776])

In [49]:
weights = torch.ones(4, requires_grad=True)
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [50]:
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [52]:
optimizer = torch.optim.SGD([weights], lr=0.01)

optimizer.step()
optimizer.zero_grad()

In [53]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [54]:
z.bakcward()
weights.grad.zero_()

AttributeError: 'Tensor' object has no attribute 'bakcward'