In [1]:
import torch


In [7]:
x = torch.rand(2, 2)
x

tensor([[0.5441, 0.7418],
        [0.9160, 0.7172]])

In [8]:
x = torch.empty(2,2)
x

tensor([[3.9973e-35, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [10]:
x = torch.zeros(2,2)
y = torch.ones(2,2)
x, y

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [12]:
z = torch.ones(4,4, dtype=torch.int)
x.dtype, z.dtype

(torch.float32, torch.int32)

In [13]:
x.size(), z.size()

(torch.Size([2, 2]), torch.Size([4, 4]))

In [14]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x, y

(tensor([[0.2776, 0.9589],
         [0.2018, 0.2798]]),
 tensor([[0.3051, 0.8000],
         [0.7222, 0.7375]]))

In [16]:
z = x + y
z

tensor([[0.5826, 1.7589],
        [0.9239, 1.0172]])

In [23]:
z = torch.add(x,y)
zmul = torch.mul(x,y)
z, zmul

(tensor([[0.3622, 1.7260],
         [0.3475, 0.4861]]),
 tensor([[0.0235, 0.7356],
         [0.0294, 0.0577]]))

In [19]:
y.add_(x)
y

tensor([[0.5826, 1.7589],
        [0.9239, 1.0172]])

In [20]:
y.sub_(x)

tensor([[0.3051, 0.8000],
        [0.7222, 0.7375]])

In [21]:
y.mul_(x)

tensor([[0.0847, 0.7671],
        [0.1457, 0.2063]])

In [25]:
x = torch.rand(5,3)
x

tensor([[0.2855, 0.1322, 0.3802],
        [0.1694, 0.5258, 0.0124],
        [0.8302, 0.6154, 0.2095],
        [0.7821, 0.5096, 0.8248],
        [0.4006, 0.6519, 0.5222]])

In [26]:
x[:, 0]

tensor([0.2855, 0.1694, 0.8302, 0.7821, 0.4006])

In [32]:
x[1, :]

tensor([0.1694, 0.5258, 0.0124])

In [33]:
x[2,2].item()

0.20949596166610718

In [35]:
x =  torch.rand(4,4)
x

tensor([[0.0400, 0.9848, 0.9247, 0.8810],
        [0.1595, 0.3037, 0.8036, 0.8784],
        [0.2062, 0.6274, 0.9443, 0.9619],
        [0.2858, 0.5540, 0.1095, 0.8242]])

In [36]:
y = x.view(16)
y

tensor([0.0400, 0.9848, 0.9247, 0.8810, 0.1595, 0.3037, 0.8036, 0.8784, 0.2062,
        0.6274, 0.9443, 0.9619, 0.2858, 0.5540, 0.1095, 0.8242])

In [37]:
y = x.flatten(0)
y

tensor([0.0400, 0.9848, 0.9247, 0.8810, 0.1595, 0.3037, 0.8036, 0.8784, 0.2062,
        0.6274, 0.9443, 0.9619, 0.2858, 0.5540, 0.1095, 0.8242])

In [39]:
y = x.view(-1, 8)
y

tensor([[0.0400, 0.9848, 0.9247, 0.8810, 0.1595, 0.3037, 0.8036, 0.8784],
        [0.2062, 0.6274, 0.9443, 0.9619, 0.2858, 0.5540, 0.1095, 0.8242]])

In [40]:
y.size()

torch.Size([2, 8])

In [41]:
import numpy as np

In [42]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [44]:
b = a.numpy()
type(b)

numpy.ndarray

In [45]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [46]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [47]:
a = np.ones(5)

In [48]:
b = torch.from_numpy(a)

In [49]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [50]:
a +=1
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [53]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
device

device(type='cpu')

In [56]:
b =  b.to(device)
b.device

device(type='cpu')

In [57]:
x = torch.ones(6, requires_grad=True)
x

tensor([1., 1., 1., 1., 1., 1.], requires_grad=True)